### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by MaxenceR26** [S0dlive/Aberant#1]
Très bon fonctionnement ! Rajouter des choses dans l'avenir..

**Comment by Kiirx** [comment]
je pense que ma réponse est bonne

**Comment by S0dlive** [comment]
vous avez raison , ce bot est magnifique

**Comment by S0dlive** [comment]
go stars : D

**Comment by Kiirx** [comment]
> vous avez raison , ce bot est magnifique

nan jrigole
